site_name: laboîte project documentation
site_author: laboîte team
copyright: 2020 © laboîte team
repo_name: laboiteproject/docs
repo_url: https://github.com/laboiteproject/docs
edit_uri: 'edit/master/src/'
docs_dir: 'src'
site_dir: 'docs'
theme:
  language: fr
  name: material
  custom_dir: overrides/material
  palette:
    primary: indigo
    accent: teal
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: fontawesome/solid/cloud
    repo: fontawesome/brands/git-alt
plugins:
  - search:
      lang:
        - fr
        - en
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/laboiteproject
    - icon: fontawesome/solid/cloud
      link: https://lenuage.io/
    - icon: fontawesome/solid/book
      link: https://docs.lenuage.io
